name: ECS Deploy
on: 
  push: 
    branches: [ "*" ]
  
jobs:
  build-bookrecs:
    permissions:
      id-token: write
      contents: read
    name: Build Docker Image
    runs-on: ubuntu-latest  
    steps:  
        - name: Checkout
          uses: actions/checkout@v4    
          
        - name: Configure AWS credentials from Primary AWS account
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::190179906259:role/github-web-identity-role
            aws-region: us-east-1
            role-session-name: gh-actions

        - name: Login to Amazon ECR
          id: login-pf-aws-ecr
          uses: aws-actions/amazon-ecr-login@v1
          

        - name: Convert to lowercase
          id: to_lowercase
          run: echo "lowercase_repo=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]' | tr --delete -)" >> $GITHUB_ENV

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.22.5

        - name: Build
          working-directory: ./
          run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o gohttp ./cmd

        - name: Build and push the tagged docker image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
            ECR_REPOSITORY: "platnation-gohttp"
#            ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
            IMAGE_TAG: latest
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
